name: dependency-check

on: [push]

jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: depcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: maven

      - name: Get Date
        id: get-date
        run: |
          echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore cached Maven dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          # Using datetime in cache key as OWASP database may change, without the pom changing
          key: ${{ runner.os }}-maven-${{ steps.get-date.outputs.datetime }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ steps.get-date.outputs.datetime }}
            ${{ runner.os }}-maven-

      - name: Build & scan
        id: scan
        run: |
          mvn -Pbedework-dev --settings ./.github/workflows/settings.xml \
            --no-transfer-progress clean package -DskipTests \
            -DnvdApiKey=${{secrets.nvdApiKey}} -DskipITs -Dmax.cvss.score=8 \
            org.owasp:dependency-check-maven:aggregate 
          #  -l ${{github.workspace}}/mvn-output.txt
          ls -al target/
          cp -r ./target/reports ${{github.workspace}}/
        #env:
        #  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME}}
        #  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD}}

      - name: Cache Maven dependencies
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ steps.get-date.outputs.datetime }}-${{ hashFiles('**/pom.xml') }}

      - name: Upload Test results
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{github.workspace}}/reports"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: depcheck
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4